# Generated by Django 3.2.6 on 2021-08-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_auto_20210827_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='postal_code',
            new_name='code',
        ),
    ]
